# 🧨04. Categorical Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
vals = pd.Series(['Axe','Axeor','Axe','Axe']*4)
vals

0       Axe
1     Axeor
2       Axe
3       Axe
4       Axe
5     Axeor
6       Axe
7       Axe
8       Axe
9     Axeor
10      Axe
11      Axe
12      Axe
13    Axeor
14      Axe
15      Axe
dtype: object

In [3]:
#in this series unique values ase are two 
#Axeor and Axe
pd.unique(vals) 

array(['Axe', 'Axeor'], dtype=object)

In [4]:
pd.value_counts(vals)

Axe      12
Axeor     4
dtype: int64

In [5]:
vals = pd.Series([0,1,0,1]*4)
vals_2 = pd.Series(['Axeor','Axe'])

In [6]:
vals

0     0
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
dtype: int64

In [7]:
vals_2

0    Axeor
1      Axe
dtype: object

In [8]:
vals_2.take(vals)

0    Axeor
1      Axe
0    Axeor
1      Axe
0    Axeor
1      Axe
0    Axeor
1      Axe
0    Axeor
1      Axe
0    Axeor
1      Axe
0    Axeor
1      Axe
0    Axeor
1      Axe
dtype: object

# 🧨4.1 Categorical Extension Type in pandas

In [9]:
color = ['black','orange','black','black']*2
n = len(color)
n

8

In [10]:
rng = np.random.default_rng(seed=12345)
rng

Generator(PCG64) at 0x7F17FEDCAAC0

In [11]:
df = pd.DataFrame({'color':color,#color name
                   'color_id':np.arange(n),#range of the color val
                   'count': rng.integers(3,15,size=n),#(3-15) random val,size is length of color 
                   'weight':rng.uniform(0,4,size=n)},#as same as count
                  columns=['color_id','color','count','weight']    
)
df

color_id   color  count    weight
0         0   black     11  1.564438
1         1  orange      5  1.331256
2         2   black     12  2.393235
3         3   black      6  0.746937
4         4   black      5  2.691024
5         5  orange     12  3.767211
6         6   black     10  0.992983
7         7   black     11  3.795525

In [12]:
#now creating categorical val 
color_cat= df['color'].astype('category')
color_cat

0     black
1    orange
2     black
3     black
4     black
5    orange
6     black
7     black
Name: color, dtype: category
Categories (2, object): ['black', 'orange']

In [13]:
c = color_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [14]:
c.categories

Index(['black', 'orange'], dtype='object')

In [15]:
dict(enumerate(c.categories))

{0: 'black', 1: 'orange'}

In [16]:
#change val in main data
df['color'] = df['color'].astype('category')
df['color']

0     black
1    orange
2     black
3     black
4     black
5    orange
6     black
7     black
Name: color, dtype: category
Categories (2, object): ['black', 'orange']

In [17]:
cate = ['Axe','Axeor','or']
codes = [0,1,2,1,0,1,0]
my_cate=pd.Categorical.from_codes(codes,cate)
my_cate

['Axe', 'Axeor', 'or', 'Axeor', 'Axe', 'Axeor', 'Axe']
Categories (3, object): ['Axe', 'Axeor', 'or']

In [18]:
my_cate.as_ordered()

['Axe', 'Axeor', 'or', 'Axeor', 'Axe', 'Axeor', 'Axe']
Categories (3, object): ['Axe' < 'Axeor' < 'or']

# 🧨4.2 Computations with Categoricals 

In [19]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws

array([-1.42382504e+00,  1.26372846e+00, -8.70661738e-01, -2.59173235e-01,
       -7.53433070e-02, -7.40884652e-01, -1.36779270e+00,  6.48892802e-01,
        3.61058113e-01, -1.95286306e+00,  2.34740965e+00,  9.68496906e-01,
       -7.59387180e-01,  9.02198274e-01, -4.66953173e-01, -6.06895187e-02,
        7.88844345e-01, -1.25666813e+00,  5.75857514e-01,  1.39897899e+00,
        1.32229806e+00, -2.99698515e-01,  9.02919341e-01, -1.62158273e+00,
       -1.58189261e-01,  4.49483932e-01, -1.34360107e+00, -8.16875907e-02,
        1.72473993e+00,  2.61815943e+00,  7.77361344e-01,  8.28633196e-01,
       -9.58988313e-01, -1.20938829e+00, -1.41229201e+00,  5.41546830e-01,
        7.51939396e-01, -6.58760320e-01, -1.22867499e+00,  2.57557768e-01,
        3.12902918e-01, -1.30811690e-01,  1.26998312e+00, -9.29624577e-02,
       -6.61508890e-02, -1.10821447e+00,  1.35956851e-01,  1.34707776e+00,
        6.11440210e-02,  7.09146003e-02,  4.33654537e-01,  2.77483660e-01,
        5.30252387e-01,  

In [20]:
draws[:10]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306])

In [21]:
#equally distributed in 4 columns 
bins = pd.qcut(draws,4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] <
                                           (0.687, 3.211]]

In [22]:
bins = pd.qcut(draws,4,labels=['q1','q2','q3','q4'])
bins

['q1', 'q4', 'q1', 'q2', 'q2', ..., 'q3', 'q3', 'q2', 'q3', 'q2']
Length: 1000
Categories (4, object): ['q1' < 'q2' < 'q3' < 'q4']

In [23]:
bins.codes[:500]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0, 3, 3, 0, 3, 1, 1, 3, 0, 2, 3, 3, 1,
       3, 0, 1, 2, 0, 1, 3, 3, 3, 3, 0, 0, 0, 2, 3, 1, 0, 2, 2, 1, 3, 1,
       1, 0, 2, 3, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 1, 2, 1, 2, 0, 0,
       3, 0, 2, 0, 0, 0, 1, 2, 0, 1, 3, 1, 0, 2, 1, 0, 0, 3, 1, 1, 0, 3,
       3, 3, 1, 2, 3, 3, 2, 1, 1, 0, 0, 2, 1, 0, 1, 3, 1, 0, 1, 3, 2, 1,
       3, 3, 1, 3, 2, 3, 3, 3, 2, 1, 0, 1, 3, 2, 2, 2, 2, 2, 0, 0, 1, 0,
       3, 1, 1, 0, 2, 1, 3, 3, 0, 2, 0, 1, 3, 3, 2, 1, 0, 0, 2, 3, 0, 2,
       2, 3, 0, 1, 2, 0, 0, 0, 1, 2, 1, 2, 0, 0, 3, 1, 1, 3, 3, 3, 2, 1,
       2, 2, 3, 2, 2, 1, 3, 0, 2, 3, 0, 3, 1, 1, 0, 3, 2, 1, 2, 2, 3, 2,
       0, 1, 0, 0, 3, 2, 1, 1, 3, 2, 3, 2, 1, 3, 0, 0, 1, 0, 1, 1, 3, 2,
       2, 0, 0, 3, 0, 3, 0, 2, 0, 2, 0, 1, 3, 1, 3, 1, 0, 2, 1, 3, 3, 3,
       2, 3, 3, 2, 0, 0, 2, 3, 3, 0, 2, 2, 0, 2, 0, 2, 3, 0, 2, 0, 0, 3,
       0, 1, 1, 1, 2, 2, 3, 3, 1, 3, 3, 0, 2, 3, 3, 2, 0, 1, 0, 1, 3, 2,
       3, 1, 0, 0, 2, 0, 1, 3, 0, 0, 1, 1, 1, 0, 2,

In [24]:
bins = pd.Series(bins,name="quartile")
bins

0      q1
1      q4
2      q1
3      q2
4      q2
       ..
995    q3
996    q3
997    q2
998    q3
999    q2
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['q1' < 'q2' < 'q3' < 'q4']

In [25]:
results  = (pd.Series(draws)
            .groupby(bins)
            .agg(['count','min','max'])
            .reset_index())
results 

quartile  count       min       max
0       q1    250 -3.119609 -0.678494
1       q2    250 -0.673305  0.008009
2       q3    250  0.018753  0.686183
3       q4    250  0.688282  3.211418

In [26]:
results['quartile']

0    q1
1    q2
2    q3
3    q4
Name: quartile, dtype: category
Categories (4, object): ['q1' < 'q2' < 'q3' < 'q4']

# 🧨4.3 Categorical Methods 

In [27]:
s = pd.Series(['Axe','Axeor','A','B']*2)
cate_s = s.astype('category')
cate_s 

0      Axe
1    Axeor
2        A
3        B
4      Axe
5    Axeor
6        A
7        B
dtype: category
Categories (4, object): ['A', 'Axe', 'Axeor', 'B']

In [28]:
cate_s.cat.codes

0    1
1    2
2    0
3    3
4    1
5    2
6    0
7    3
dtype: int8

In [29]:
cate_s.cat.categories

Index(['A', 'Axe', 'Axeor', 'B'], dtype='object')

In [31]:
actual_categories =['Axe','Axeor','A','B','D',"E" ]
cate_s2 = cate_s.cat.set_categories(actual_categories)
cate_s2

0      Axe
1    Axeor
2        A
3        B
4      Axe
5    Axeor
6        A
7        B
dtype: category
Categories (6, object): ['Axe', 'Axeor', 'A', 'B', 'D', 'E']

In [35]:
cate_s.value_counts()

A        2
Axe      2
Axeor    2
B        2
dtype: int64

In [36]:
cate_s2.value_counts()

Axe      2
Axeor    2
A        2
B        2
D        0
E        0
dtype: int64

In [38]:
cate_s3 =cate_s[cate_s.isin(['A','Axe'])]
cate_s3

0    Axe
2      A
4    Axe
6      A
dtype: category
Categories (4, object): ['A', 'Axe', 'Axeor', 'B']

In [39]:
cate_s3.cat.remove_unused_categories()

0    Axe
2      A
4    Axe
6      A
dtype: category
Categories (2, object): ['A', 'Axe']